# Generated by Django 5.1.4 on 2024-12-22 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_books_book_is_avai_0e7459_idx'),
        ('borrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='returned',
            new_name='is_returned',
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['book'], name='borrow_borr_book_id_ba1be4_idx'),
        ),
        migrations.AddIndex(
            model_name='borrow',
            index=models.Index(fields=['user', 'is_returned'], name='borrow_borr_user_id_7ee0b0_idx'),
        ),
    ]
