# Generated by Django 5.1.4 on 2024-12-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_book_is_available'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_available', 'available_copies'], name='books_book_is_avai_0e7459_idx'),
        ),
    ]
